version: '2'

services:
    nginx:
        extends:
            file: docker-common.yml
            service: nginx
        ports:
            - 8000:8000
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - backend
    mariadb:
        image: mariadb
        volumes:
            - ./docker/mariadb:/data
        command: --init-file /data/init_db.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mariadb:/mariadb
        entrypoint:
            - /mariadb/db-entrypoint.sh
    backend:
        extends:
            file: docker-common.yml
            service: django
        links:
            - mariadb
        entrypoint:
            - /django-entrypoint.sh
        expose:
            - 8000
    frontend:
        extends:
            file: docker-common.yml
            service: web
        links:
            - backend
        entrypoint:
            - /web-entrypoint.sh
    redis:
        image: "redis:alpine"
        ports:
          - "6373:6373"
        container_name: redis
